[features]
seeds = false
[programs.localnet]
hello_anchor = "GzScbxmzfKMTV7NdfNDF5f4C8EtRtzR3aB8VzgM5g24s"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/rolandgavrilescu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
